version: "3"

services:
  tc-server:
    image: "jetbrains/teamcity-server" # the official JetBrains image
    volumes:
      - "/opt/teamcity/data:/data/teamcity_server/datadir"
      - "/opt/teamcity/log:/data/teamcity/logs"
    ports:
      - 8111:8111
    env_file:
      - encrypt.env
      - teamcity.env

  tc-agent:
    image: "jetbrains/teamcity-minimal-agent" #the official JetBrains image
    env_file:
      - teamcity.env

  # letsencrypt-companion:
  #   image: jrcs/letsencrypt-nginx-proxy-companion
  #   restart: always
  #   volumes:
  #     - certs:/etc/nginx/certs
  #     - vhost.d:/etc/nginx/vhost.d
  #     - html:/usr/share/nginx/html
  #     - /var/run/docker.sock:/var/run/docker.sock:ro
  #   networks:
  #     - proxy-tier
  #   depends_on:
  #     - proxy

volumes:
  tc-server:
  tc-agent:
  certs:
# networks:
#   proxy-tier:
